# Generated by Django 4.2.30 on 2026-07-27 23:14

from django.db import migrations, models
import utils.base_models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataChangesAndSuspectedActivity',
            fields=[
                ('id', utils.base_models.GenericPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, help_text='System or user', max_length=1000, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
