# Generated by Django 4.2.30 on 2026-07-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsworkschedulemodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsworkschedulemodel',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userunavailabilitymodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userunavailabilitymodel',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
