# Generated by Django 4.2.30 on 2026-07-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_alter_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
