# Generated by Django 4.2.30 on 2026-07-28 14:25

import acl.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', acl.models.CustomUserManager()),
            ],
        ),
    ]
