# Generated by Django 4.2.30 on 2026-07-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_appointmentsmodel_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentsmodel',
            old_name='target_user',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointmentsmodel',
            old_name='public_user',
            new_name='patient',
        ),
    ]
