# Generated by Django 4.2.30 on 2026-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_target_user_appointmentsmodel_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentsmodel',
            old_name='public_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='public_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
