# Generated by Django 4.2.30 on 2026-07-28 22:43

from django.db import migrations, models
import django.db.models.deletion
import utils.base_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_public_status_appointmentsmodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='public_remarks',
        ),
        migrations.CreateModel(
            name='AppointmentRemarksModel',
            fields=[
                ('id', utils.base_models.GenericPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('remark_for', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='bookings.appointmentsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
