

name: Final Deploy CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

  serve_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Validate OpenAPI Document
        run: npx @scalar/cli document validate docs/openapi.yaml

      - name: Push to Registry
        run: |
          npx @scalar/cli registry publish \
            --namespace default-team-vvlfo \
            --slug myclinic-api \
            docs/openapi.yaml